USE shoply;
-- 1.CLEANING CUSTOMER TABLE.
-- REPLACING NULL VALUES IN CITY COLUMN WITH UNKNOWN
UPDATE customers 
SET city="unknown"
WHERE city IS NULL;

-- SAFE MODE HAS TURNED OFF
SET SQL_SAFE_UPDATES=0; 

-- REMOVE INCONSISTENCY,MAKE ALL CITIES STARTING WITH CAPITAL
UPDATE customers 
SET city =CONCAT(UPPER(LEFT(city,1)),LOWER(SUBSTRING(city,2)))
WHERE city !="unknown";

-- IF EMAIL DUPLICATED,THEN DELETE THE ONE HAVING MAX CUST ID
DELETE FROM customers    
WHERE customer_id 
NOT IN (
SELECT MIN(customer_id),email
FROM customers
GROUP BY email);

-- STANDARDIZE EMAIL INTO LOWERCASE
UPDATE customers
SET email = LOWER(email);

-- TRIM EXTRA SPACES FROM CUSTOMERS NAME AND CITIES
UPDATE customers
SET customer_name=TRIM(customer_name);
UPDATE customers
SET city=TRIM(city);






